"""The coach's written conclusions. Numbers come from data/*.profile.json and explore.py;
edit this file after a refresh when the conclusions change, then run build_report.py."""

ME = {
    "date": "26 Sep 2026",
    "footer": "17 of your games since March 2022, 2,946 of Etienne's and 6,276 of Greg's from the last 12 months",
    "summary": "You play active, developing chess and win fast when you get the initiative: 6 of your 7 games under 25 moves were wins and the other was a draw. The problem is what happens next. You reach winning positions often, then hand them back with one oversight. Most of your losses come from one habit, and it's fixable.",
    "stats": [("1208", "Rapid rating (daily 967)"), ("17", "Games on record since 2022"),
              ("72%", "Opponent blunders you punished"), ("9 of 14", "Winning positions (+3) you converted"),
              ("1 of 8", "Losing positions you saved")],
    "strengths": [
        "Your openings are clean. You blunder 3.1 times per 100 opening moves, less than half your middlegame rate.",
        "You spot free material. When an opponent blundered, you found the refutation 72% of the time (13 of 18).",
        "With 1.d4 and a quick Bf4/Nc3/Nf3 setup you scored 75% (4 games). You get a comfortable position and an easy plan.",
        "You castle early (kingside, around move 12) and keep your king safe.",
    ],
    "weaknesses": [
        "<b>You give back won games.</b> Five of your biggest blunders came when you were already +5 or better: 17.Nxh8 vs Etienne, 10.Ng6+ vs Etienne, 9.Bb5+, 15…h5 vs Greg and 26…Rff8.",
        "<b>You miss what the last move changed.</b> Etienne's …e5 opened his bishop onto your queen. …Nc3 hit your queen. Greg's h4 left a knight to be taken. Each time you played your own plan.",
        "<b>Middlegame accuracy:</b> 7.2 blunders per 100 middlegame moves, about the same rate as Etienne (7.5).",
        "<b>Once you're worse, games get away.</b> You saved 1 of 8 lost positions and scored 33% in games of 25–45 moves.",
        "<b>The clock:</b> 2 of your 7 losses were on time, both in rapid or blitz.",
    ],
    "puzzles": [
        {"game": "vs Etienne · daily · Feb 2025 · move 17", "fen": "2k2r1r/pppb2p1/2nb1qNp/3pp3/1P1P1PQ1/N1PB3R/P5PP/R1B3K1 w - - 0 17",
         "played": "Nxh8", "best": "Qh4", "loss": 79.7,
         "prompt": "Etienne just played …e5. The rook on h8 is hanging. What else changed?",
         "why": "…e5 opened the d7 bishop's diagonal to your queen on g4. Qh4 keeps the queen safe and keeps the attack (+5.5). After Nxh8 Bxg4 you were down a queen and lost."},
        {"game": "vs Greg · blitz 3|0 · Aug 2022 · move 15", "fen": "r1bq2kr/ppp5/3p1n1p/3Np3/1P1nP1pP/P2P4/2P2PP1/R1BQ1RK1 b - h3 0 15",
         "played": "h5", "best": "Nxd5", "loss": 73.1,
         "prompt": "Greg just pushed h2–h4 next to his king. How do you punish it?",
         "why": "Nxd5 exd5 removes the knight, then Qxh4 lines your queen up with the rook on the h-file against his bare king (+8). Your h5 closed the file you needed."},
        {"game": "vs gooby213 · rapid · Mar 2022 · move 16", "fen": "r2qk2r/p4pbp/1p1p2p1/1N2p3/1Pn5/P1n1BN2/2P2PPP/R2Q1RK1 w kq - 2 16",
         "played": "Qd3", "best": "Nxc3", "loss": 56.7,
         "prompt": "A black knight just landed on c3 and attacks your queen. What's the simplest reply?",
         "why": "Nxc3 captures the attacker, and you stay a piece up (+5.7). Moving the queen away left both black knights alive, and you lost material."},
        {"game": "vs Etienne · daily · Mar 2022 · move 10", "fen": "rn2kb1r/pp3ppp/5n2/1N1qN3/3p4/8/PPPPQPPP/R1B1K2R w KQkq - 2 10",
         "played": "Ng6+", "best": "Nc7+", "loss": 34.5,
         "prompt": "Both of your knights are near his king. Which check wins the most?",
         "why": "Nc7+ forks the king and the queen on d5 and wins the queen (+10). Ng6+ was a nice-looking check that won nothing. When you have several checks, work out what each one attacks."},
    ],
    "training": [
        "<b>Blunder check before every move:</b> \"What did their last move attack or uncover? What's hanging now?\" Only then play your own idea. This one habit would have saved four of the drills on this page.",
        "<b>When you're winning, play safe:</b> before grabbing material, ask \"what can they take after I take?\" Trade pieces and take the simple win.",
        "<b>15 minutes of puzzles a day</b> on chess.com. Choose the Discovered Attack, Fork and Hanging Piece themes, which are the exact patterns you missed.",
        "<b>Play a few rapid 15|10 games a week.</b> With 17 rated games your ratings are still unreliable, and more games will sharpen the profile I build on you.",
    ],
}

FRIENDS = {
    "pepex654": {
        "name": "Etienne", "anchor": "etienne",
        "summary": "A committed 1.e4 player with an enormous blitz habit (2,805 games of 5|0 this year). He plays the same openings every time, so preparing is straightforward. His Petrov contains a repeated error that loses a pawn by force. He gets better as the board empties, so win the game in the middlegame.",
        "stats": [("1114", "Blitz 5|0 (2,805 games this year)"), ("1119", "Daily"), ("1039", "Rapid, his lowest rating"),
                  ("4–1–1", "Your record vs him (daily)"), ("7.5", "Middlegame blunders per 100 moves")],
        "style": [
            "Always 1.e4. Against 1…e5 he always plays the Scotch (3.d4, 468 of 473 games).",
            "As Black he answers 1.e4 e5 2.Nf3 with the Petrov, 2…Nf6. Against 1.d4 he plays 1…e6, then …d5 and …Bd6.",
            "He castles queenside in about a quarter of his games and likes to attack. That's how he beat you in 2025.",
            "He's good on the clock. He wins on time almost twice as often as he loses on time.",
            "His endgames are clean: 3.2 blunders per 100 endgame moves, and he scores 53% in games of 45+ moves.",
        ],
        "weak": [
            "<b>The Petrov …Bc5.</b> After 3.Bc4 or 3.Nc3 he plays …Bc5 in 118 games, and 4.Nxe5 wins a pawn every time. The engine flagged it as his most repeated opening mistake.",
            "Middlegame accuracy is his weak phase: 7.5 blunders per 100 moves, twice his opening and endgame rates.",
            "He scores 40% against 4…Nf6 in the Scotch (20 games) and 33% after 6…Bb4.",
            "He converted only 60% of his winning positions, so don't resign.",
        ],
        "plans": [
            {"eyebrow": "You have White", "title": "1.e4 e5 2.Nf3 Nf6 3.Bc4! and wait for …Bc5",
             "body": [
                 "He answers 3.Bc4 with 3…Bc5 in 85 of 102 games. That move is a mistake: <b>4.Nxe5!</b> takes a free pawn.",
                 "His usual reply is 4…Qe7 (10 of 13). Then <b>5.Bxf7+! Kf8 6.d4!</b> and you're about four pawns up. 6.d4 blocks the queen's attack on e5 and hits the bishop at the same time. <b>Don't play 6.Bb3??</b>, because 6…Qxe5 wins your knight back.",
                 "If he plays 4…O-O instead, play 5.d4. The bishop has to retreat and you keep the extra pawn.",
                 "If he avoids it with 3…d6 (he scores 25% there), just develop: 4.Nc3, 5.d3 and 0-0.",
             ],
             "table": [("3.Bc4 Bc5", 85, "47%"), ("3.Bc4 d6", 14, "25%"), ("3.Nc3 Bc5", 33, "35%"), ("4.Nxe5 Qe7", 10, "60%*")],
             "line": "e4 e5 Nf3 Nf6 Bc4 Bc5 Nxe5 Qe7 Bxf7+ Kf8 d4", "key_from": 6,
             "caption": "Gold moves are the trap. *His opponents mostly played 5.Nxf7 here, which lets him back into the game."},
            {"eyebrow": "You have Black", "title": "1.e4 e5 2.Nf3 Nc6 3.d4 exd4 4.Nxd4 Nf6!",
             "body": [
                 "You already play 1…e5, so keep it. He'll play the Scotch. Instead of the popular 4…Bc5 (he scores 54% there), play <b>4…Nf6</b>. He always answers 5.Nxc6 bxc6 6.Nc3, and he scores 38% from that position.",
                 "Then play <b>6…Bb4</b>, pinning the knight and pressuring e4. Against 7.Bd2 or 7.Qd4, play 7…Qe7. Against 7.Qd3, castle. Follow with …d5 and …O-O. Engine: equal to slightly better for Black.",
                 "Your c6 pawn supports …d5, and your rook goes to the open b-file.",
             ],
             "table": [("4…Bc5", 68, "54%"), ("4…Nxd4", 204, "61%"), ("4…Nf6", 20, "40%"), ("6…Bb4", 9, "33%")],
             "line": "e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Nf6 Nxc6 bxc6 Nc3 Bb4 Bd2 Qe7", "flip": True, "key_from": 7,
             "caption": "Board is shown from Black's side."},
        ],
        "checklist": [
            "Ask for <b>rapid 15|10 or a daily game</b>. Rapid is his lowest rating (1039, yours is 1208), and at 5|0 he has thousands of games of practice.",
            "As White: 3.Bc4 and hope for …Bc5. After 4.Nxe5 Qe7 5.Bxf7+ Kf8, play <b>6.d4!</b> (not Bb3).",
            "As Black: 4…Nf6 in the Scotch, then …Bb4, …Qe7, …d5.",
            "Decide the game in the middlegame. Keep pieces on and don't head for a level endgame, which is his best phase.",
            "If he castles queenside, attack there with pawns and watch for sacrifices on your own king. That's how he beat you in 2025.",
        ],
    },
    "gregmolin": {
        "name": "Greg", "anchor": "greg",
        "summary": "A bullet specialist: 6,038 one-minute games this year, and about two-thirds of all his games end on the clock. He plays 1.e4 with 2.Nc3 on autopilot and replies to 1.d4 with 1…d5 2.Bf4 Nc6. Both habits run into prepared traps. Slow the game down and he loses his biggest weapon.",
        "stats": [("879", "Bullet 1|0 (6,038 games this year)"), ("977", "Blitz 3|0"), ("1043", "Daily"),
                  ("2–3", "Your record vs him (2022, casual)"), ("38%", "His score vs 1.d4 in slower games")],
        "style": [
            "Always 1.e4, and 2.Nc3 against almost everything: the Vienna and Four Knights against 1…e5, and 2.Nc3 against the Caro-Kann.",
            "As Black he plays 1…e5 against 1.e4. In bullet he sometimes plays the Scandinavian, but not in slower games. Against 1.d4 he plays 1…d5, and after 2.Bf4 he plays 2…Nc6 in 100 of 140 games.",
            "He castles kingside early (around move 9) and plays quickly. In blitz he wins on time more often than he loses on time.",
            "He's stubborn. He saved a third of his lost positions and rarely resigns, so you have to finish the job.",
            "His endgames are tidy: 3.4 blunders per 100 endgame moves.",
        ],
        "weak": [
            "<b>Slow games expose him.</b> Against 1.d4 in blitz, rapid or daily he scores just 38%.",
            "<b>His London setup with …Nc6</b> leaves c7 weak. After 3.Nc3 Nf6 he scores 38%, and 4.Nb5! sets a trap that wins a rook against every natural reply.",
            "<b>The Caro-Kann:</b> after 2.Nc3 d5 3.exd5 cxd5 4.d4 he scores 35% (91 games). After 3.Nf3 dxe4 4.Nxe4 Bf5 5.d3 he scores 25%.",
            "He's loose in the opening, with 4.3 blunders per 100 opening moves (Etienne has 3.4), and loose in the middlegame (7.1).",
        ],
        "plans": [
            {"eyebrow": "You have White", "title": "1.d4 d5 2.Bf4 Nc6 3.Nc3 Nf6 4.Nb5!",
             "body": [
                 "This is your own setup: d4, Bf4 and Nc3. Against Greg's …Nc6, the knight jump to b5 targets c7, and your Bf4 already covers that square.",
                 "Every natural reply (4…Bf5, 4…e6, 4…Bg4, 4…a6) loses to <b>5.Nxc7+</b>. It forks the king and the a8 rook, and he can't take back because Bf4 covers c7. That's +6 for White.",
                 "Only 4…e5! holds. Then 5.Bxe5 Nxe5 6.dxe5 and you're still better (+0.8): his knight has to move and you keep a healthy extra-space position.",
                 "If he plays 2…Nf6 instead, play 3.Nc3 anyway (he scored 0 of 3 against it) and continue with e3, Nf3, Bd3 and O-O.",
             ],
             "table": [("1.d4 (slower games)", 26, "38%"), ("2.Bf4 Nc6 3.Nc3", 10, "30%"), ("3…Nf6 4.Nb5 (engine)", "–", "+6 unless 4…e5")],
             "line": "d4 d5 Bf4 Nc6 Nc3 Nf6 Nb5 Bf5 Nxc7+ Kd7 Nxa8", "key_from": 6,
             "caption": "Gold moves are the trap, shown with 4…Bf5. The same fork works after …e6, …Bg4 or …a6."},
            {"eyebrow": "You have Black", "title": "1.e4 c6! The Caro-Kann against 2.Nc3",
             "body": [
                 "Greg plays 2.Nc3 against almost everything, and against the Caro-Kann it gets him nothing. Structurally this is his worst opening: <b>35% in 91 games</b> after 3.exd5 cxd5 4.d4.",
                 "Main line: 2.Nc3 d5 3.exd5 cxd5 4.d4 Nf6 5.Be3 <b>Bf5!</b> (he scores 10% there). Then …e6, …Nc6, …Bd6 and castle. Engine: dead equal, and you get a comfortable plan while he has none.",
                 "If he plays 3.Nf3: 3…dxe4 4.Nxe4 Bf5 5.d3 (he plays this 8 times in 10) e6, then …Nd7, …Ngf6 and …Be7. He scores 25% from there.",
                 "The Caro-Kann is solid, and that suits you: fewer early tactics to blunder into, and a long game that tests his patience instead of his hands.",
             ],
             "table": [("2.Nc3 d5 3.exd5 cxd5 4.d4", 91, "35%"), ("…5.Be3 Bf5", 5, "10%"), ("3.Nf3 dxe4 4.Nxe4 Bf5 5.d3", 8, "25%")],
             "line": "e4 c6 Nc3 d5 exd5 cxd5 d4 Nf6 Be3 Bf5 Nf3 e6", "flip": True, "key_from": 1,
             "caption": "Board is shown from Black's side."},
        ],
        "checklist": [
            "<b>Never play him at bullet or 3|0.</b> Ask for rapid 15|10 or daily, where his 6,000 bullet games don't help him.",
            "As White: 1.d4, 2.Bf4, 3.Nc3. If he plays …Nc6 and …Nf6, jump <b>4.Nb5</b> and look for Nxc7+.",
            "As Black: 1…c6. After 3.exd5 cxd5 4.d4 Nf6 5.Be3, play …Bf5.",
            "He plays fast. Use your own time to blunder-check his fast moves, because they'll be looser than they look.",
            "He doesn't resign. When you're winning, simplify and take the safe route. Don't give him swindle chances.",
        ],
    },
}
